# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.8.5
  # 版权年份
  copyrightYear: 2023
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  # profile: D:/ruoyi/uploadPath
  profile: C:/PMP/LabSystem/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8095
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 指定编码格式
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  # 应用程序的环境配置
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 50MB
      # 设置总上传的文件大小
      max-request-size: 200MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: 10.52.6.32
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

#  # 发送邮件配置
#  mail:
#    # 配置 smtp 服务器地址
#    host: smtp.qq.com
#    # smtp 服务器端口
#    port: 587
#    # 配置邮箱用户名
#    username: 3303850545@qq.com
#    # 配置申请到的授权码
#    password: lsaihupeswnacief
#    # 配置邮件编码
#    default-encoding: UTF-8
#    properties:
#      mail:
#        smtp:
#          # 配置 SSL 加密工厂
#          socketFactoryClass: javax.net.ssl.SSLSocketFactory
#        debug: true
#    # 发送方邮件
#    from: 3303850545@qq.com

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: tydhyszjlsz09*
  # 令牌有效期（默认30分钟）
  # expireTime: 30
  # 7天
  expireTime: 10080
  # 是否允许并多设备登录   true:允许  false:不允许
  soloLogin: false

# MyBatis Plus配置
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.ruoyi.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  # 配置数据库方言
  helperDialect: sqlserver
  # 确保用户输入的页数不在合法范围时能够响应到正确的结果页面，
  reasonable: true
  # 支持通过Mapper接口参数来传递分页参数
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping:

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 集成actuator实现优雅关闭应用
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "shutdown"
      base-path: /monitor
